In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.spatial.distance import squareform
from sklearn.metrics.pairwise import cosine_similarity, euclidean_distances

import os 
EMBEDDING_DATA_DIR = '/home/hhansen/decon/decon_env/data'
os.environ['EMBEDDING_DATA_DIR'] = EMBEDDING_DATA_DIR
os.environ['DATA_DIR'] = '/home/hhansen/decon/decon_env/DecontextEmbeddings/data'
os.environ['EMBEDDING_EVALUATION_DATA_PATH'] = '/home/hhansen/decon/decon_env/DecontextEmbeddings/helpers/embedding_evaluation/data/'

from scipy.stats import spearmanr, pearsonr
from scipy.spatial.distance import squareform
import numpy as np 
from collections import defaultdict

import os 
import sys 
sys.path.append('/home/hhansen/decon/decon_env/DecontextEmbeddings')

from helpers.things_evaluation.evaluate import read_embeddings, load_behav, load_sorting, match_behv_sim, evaluate as run_evaluation
from helpers.plot import get_ax
from helpers.data import load_things_database

/home/hhansen/decon/decon_env/DecontextEmbeddings/data

In [5]:
things = load_things_database()
things[['Word', 'uniqueID', 'COCA word freq (online)', 'Wordnet ID2', 'Wordnet ID4', 'All Bottom-up Categories']]

,Word,uniqueID,COCA word freq (online),Wordnet ID2,Wordnet ID4
0,aardvark,aardvark,53,aardvark%1:05:00::,aardvark.n.01
1,abacus,abacus,188,abacus%1:06:00::,abacus.n.02
2,accordion,accordion,816,accordion%1:06:00::,accordion.n.01
3,acorn,acorn,1289,acorn%1:20:00::,acorn.n.01
4,air conditioner,air_conditioner,943,air_conditioner%1:06:00::,air_conditioner.n.01
...,...,...,...,...,...
1849,yoke,yoke,692,yoke%1:06:00::,yoke.n.07
1850,yolk,yolk,881,yolk%1:13:00::,yolk.n.01
1851,zebra,zebra,1066,zebra%1:05:00::,zebra.n.01
1852,zipper,zipper,1478,zipper%1:06:00::,zipper.n.01
1853,zucchini,zucchini,2098,zucchini%1:13:00::,zucchini.n.02